#!/bin/bash

for var in "$@"
do
    case $var in
        "compile")
            mkdir obj &> /dev/null
            avr-g++ -mmcu=atmega328pb -I src/ -Os src/*.c -Os src/*.cpp -o obj/quadronecarlos.o
        ;;
        "build")
            mkdir hex &> /dev/null
            avr-objcopy -j .text -j .data -O ihex  obj/quadronecarlos.o  hex/quadronecarlos.hex
        ;;
        "upload")
            avrdude -c usbtiny -p m328pb -P usb -U flash:w:hex/quadronecarlos.hex
        ;;
        "size")
            avr-size hex/quadronecarlos.hex
        ;;
        "clean")
            rm -rf obj/ hex/ &> /dev/null
        ;;
        "all")
            $0 compile build
        ;;
        "re")
            $0 clean all
        ;;
        "help")
            printf "QuadroneCarlos v1.0\n\n"
            
            printf "Usage:\n"
            printf "\t%s [argument]\n\n" $0
            
            printf "Arguments:\n"
            printf "\t help\t-\t open current help view\n"
            printf "\t compile\t-\t generate object files\n"
            printf "\t build\t-\t generate hex file\n"
            printf "\t upload\t-\t ...\n"
            printf "\t size\t-\t ...\n"
            printf "\t clean\t-\t delete all object and hex files\n"
            printf "\t all\t-\t compile & build\n"
            printf "\tre\t-\t clean & all\n\n"
        ;;
        *)
            printf "Bad argument: %s" $var
            break 2
    esac
done