#!/bin/bash

for var in "$@"
do
    case $var in
        compile|c)
            mkdir obj &> /dev/null
            avr-g++ -mmcu=atmega328pb -I src/ -Os src/*.c -Os src/*.cpp -o obj/quadronecarlos.o
        ;;
        build|b)
            mkdir hex &> /dev/null
            avr-objcopy -j .text -j .data -O ihex  obj/quadronecarlos.o  hex/quadronecarlos.hex
        ;;
        upload|u)
            avrdude -c usbtiny -p m328pb -P usb -U flash:w:hex/quadronecarlos.hex
        ;;
        size|s)
            avr-size hex/quadronecarlos.hex
        ;;
        clean|C)
            rm -rf obj/ hex/ &> /dev/null
        ;;
        all|a)
            $0 compile build
        ;;
        re|r)
            $0 clean all
        ;;
        help|h)
            printf "QuadroneCarlos v1.0\n\n"
            
            printf "Usage:\n"
            printf "            %s [argument]\n\n" $0
            
            printf "Arguments:\n"
            printf "            help       - open current help view\n"
            printf "            compile    - generate object files\n"
            printf "            build      - generate hex file\n"
            printf "            upload     - write hex file to MCU memory\n"
            printf "            size       - displays the sizes of sections inside hex file\n"
            printf "            clean      - delete all objects and hex files\n"
            printf "            all        - compile & build\n"
            printf "            re         - clean & all\n\n"
        ;;
        *)
            printf "Bad argument: %s" $var
            break 2
    esac
done